const kind=document.body.dataset.demo;
const $=s=>document.querySelector(s);
const products=[['Trail',32],['Summit',27],['Daybreak',35],['Stream',19],['Roam',24],['Ridge',19]];
const guesses=['123456','password','qwerty','letmein','welcome','abc123'];
const boards={win:['X','O','','X','O','','','',''],block:['O','O','','X','','','','X',''],draw:['X','O','X','X','O','','O','X','']};
const titles={price:['Find the lowest price.','The product shelf'],board:['Find the best next move.','The game board'],password:['A password guessing loop.','The simulation']};
const codes={price:['best_price = float("inf")','best_product = None','for i in range(len(products)):','    price = products[i]["price"]','    if price < best_price:','        best_price = price','        best_product = products[i]["name"]'],board:['best_score = -2','best_move = None','for i in range(9):','    if board[i] != "":','        continue','    score = outcome_if_x_plays(board, i)','    if score > best_score:','        best_score = score','        best_move = i'],password:['found = False','for i in range(len(common_passwords)):','    guess = common_passwords[i]','    if simulated_login(guess):','        found = True','        break','    if locked_out():','        break']};
const explanations={price:'The highlighted lines run once for the current product. “Best so far” changes only when the new price is lower. Infinity lets the first price become the initial best.',board:'The board is a list of 9 cells, indexed left to right, top to bottom. The helper uses minimax internally; students can treat it as a supplied function and focus on the for loop.',password:'Both helper functions are local simulations. simulated_login compares the guess with a preset value and counts attempts. locked_out is true after three failed attempts when protection is enabled. No requests or real accounts are involved.'};
const t=titles[kind];
document.title=t[0];
$('#app').innerHTML=`<div class="shell"><nav aria-label="Demos"><a href="../index.html">All demos</a><a href="index.html" ${kind==='price'?'aria-current="page"':''}>01 · Prices</a><a href="tic-tac-toe.html" ${kind==='board'?'aria-current="page"':''}>02 · Tic-tac-toe</a><a href="passwords.html" ${kind==='password'?'aria-current="page"':''}>03 · Passwords</a><a href="${({price:'prices-large.html',board:'go-large.html',password:'passwords-large.html'})[kind]}">Large version →</a><a href="references.html">Object references</a></nav><header><h1>${t[0]}</h1></header><main><div class="layout"><section class="panel"><div class="panel-head"><h2>${t[1]}</h2><span class="tag" id="progress">Ready</span></div><div class="scene" id="scene"></div><div class="status" aria-live="polite"><strong id="statusTitle"></strong><span id="statusText"></span></div><div class="controls"><button class="primary" id="step">Step →</button><button id="play">▶ Play</button><button id="reset">Reset</button><label>Speed <select id="speed"><option value="1600">Slow</option><option value="900" selected>Normal</option><option value="400">Fast</option></select></label></div></section><section class="panel code-panel"><div class="panel-head"><h2>The loop</h2><span class="tag">Python · one step = one iteration</span></div><pre class="code" aria-label="Python code"><code id="code"></code></pre><div class="variables" id="variables"></div><p class="explain">${explanations[kind]}</p></section></div></main><footer>Amber = current item; labeled green = best or match<div class="credit"><strong>UC Merced CSE019 Fall 2026</strong><br>Instructor: Ryan Zhiyu An<br>© 2026 Ryan Zhiyu An · <a rel="license" href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a> · Noncommercial use only<br><a href="https://github.com/ryeii/UCM-CSE019-Demos">Source code on GitHub</a></div></footer></div>`;
$('#code').innerHTML=codes[kind].map((l,i)=>`<span class="line" data-line="${i}"><span class="ln">${i+1}</span>${l.replaceAll('&','&amp;').replaceAll('<','&lt;')}</span>`).join('');
let state,timer=null,scenario='win',strong=false,protectedLogin=false;
function stop(){clearInterval(timer);timer=null;$('#play').textContent='▶ Play'}
function highlight(lines){document.querySelectorAll('.line').forEach((e,i)=>e.classList.toggle('active',lines.includes(i)))}
function status(title,detail){$('#statusTitle').textContent=title;$('#statusText').textContent=detail}
function vars(pairs){$('#variables').innerHTML=pairs.map(([k,v])=>`<div class="variable"><small>${k}</small><strong>${v}</strong></div>`).join('')}
function finish(){state.done=true;stop();$('#step').disabled=true;$('#play').disabled=true}
function reset(){stop();state={i:-1,best:Infinity,bestIndex:null,scores:{},done:false,found:false};if(kind==='board')state.best=-2;$('#step').disabled=false;$('#play').disabled=false;highlight([0,...(kind==='password'?[]:[1])]);status('Ready to loop','Predict the result, then press Step to inspect the first item.');$('#progress').textContent='0 / '+(kind==='board'?9:6)+' visited';render()}
function winner(b){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return null}
function minimax(b,turn){const w=winner(b);if(w)return w==='X'?1:-1;if(b.every(Boolean))return 0;let best=turn==='X'?-2:2;for(let i=0;i<9;i++){if(b[i])continue;b[i]=turn;const value=minimax(b,turn==='X'?'O':'X');b[i]='';best=turn==='X'?Math.max(best,value):Math.min(best,value)}return best}
function scoreMove(b,i){const copy=[...b];copy[i]='X';return minimax(copy,'O')}
function render(){const i=state.i;
 if(kind==='price'){$('#scene').innerHTML=`<div class="products">${products.map(([name,p],j)=>`<div class="product ${j===i?'active':''} ${j===state.bestIndex?'best':''}"><div class="art"><div class="bottle" style="--bottle:${['#739a86','#98a3bd','#c49975','#6a9ca5','#b09baf','#8b9b6c'][j]}"></div></div><h3>${name}</h3><strong>$${p}</strong><div class="item-note">i = ${j} · ${j===state.bestIndex?'BEST SO FAR':j===i?'CHECKING':j<i?'visited':'not visited'}</div></div>`).join('')}</div>`;vars([['i',i<0?'—':i],['best_price',state.best===Infinity?'∞':'$'+state.best],['best_product',state.bestIndex===null?'None':products[state.bestIndex][0]]]);}
 if(kind==='board'){const b=boards[scenario];$('#scene').innerHTML=`<label class="scenario">Position <select id="scenario"><option value="win">Find a winning move</option><option value="block">Block the opponent</option><option value="draw">Save a draw</option></select></label><div class="board" aria-label="Tic-tac-toe board">${b.map((mark,j)=>`<div class="cell ${j===i?'active':''} ${j===state.bestIndex?'best':''}"><span class="index">${j}</span><span class="mark ${mark==='O'?'o':''}">${mark||'·'}</span><small>${state.scores[j]!==undefined?'score '+(state.scores[j]>0?'+':'')+state.scores[j]:j<=i&&mark?'skip':''}</small><small>${j===state.bestIndex?'BEST SO FAR':''}</small></div>`).join('')}</div><div class="legend">X moves next · +1 win / 0 draw / −1 loss</div>`;$('#scenario').value=scenario;$('#scenario').onchange=e=>{scenario=e.target.value;reset()};vars([['i',i<0?'—':i],['best_score',state.best],['best_move',state.bestIndex??'None']]);}
 if(kind==='password'){$('#scene').innerHTML=`<label class="scenario">Account <select id="account"><option value="common">Common password: welcome</option><option value="strong">Password absent from the list</option></select></label><label class="check"><input type="checkbox" id="protection" ${protectedLogin?'checked':''}> Lock out after 3 failed attempts</label><div class="password-scene"><div class="guesses">${guesses.map((g,j)=>`<div class="guess ${j===i?'active':''} ${state.found&&j===i?'match':''}"><span>${g}</span><small>${j===i&&state.found?'MATCH':j<=i?'failed':'waiting'}</small></div>`).join('')}</div><div class="terminal"><small>LOCAL TRAINING ACCOUNT</small><div class="lock" aria-hidden="true">${state.found?'◇':'▣'}</div><h3>student_demo</h3><p>guess: ${i<0?'—':guesses[i]}</p><p class="result">${state.found?'ACCESS GRANTED':state.done&&protectedLogin&&i===2?'ACCOUNT LOCKED':i<0?'AWAITING ATTEMPTS':'ACCESS DENIED'}</p><small>Only preset values are compared in this browser.</small></div></div>`;$('#account').value=strong?'strong':'common';$('#account').onchange=e=>{strong=e.target.value==='strong';reset()};$('#protection').onchange=e=>{protectedLogin=e.target.checked;reset()};vars([['i',i<0?'—':i],['attempts',i+1],['found',state.found?'True':'False']]);}
}
function step(){if(state.done)return;state.i++;const i=state.i;const count=kind==='board'?9:6;$('#progress').textContent=`${i+1} / ${count} visited`;
 if(kind==='price'){const [name,p]=products[i],old=state.best,better=p<old;if(better){state.best=p;state.bestIndex=i}highlight(better?[2,3,4,5,6]:[2,3,4]);status(better?'Update the best price':'Keep the current best',`i = ${i}: $${p} < ${old===Infinity?'∞':'$'+old} is ${better?'True':'False'}. ${better?name+' becomes the best so far.':'The best remains '+products[state.bestIndex][0]+'.'}`);if(i===count-1){finish();status('Lowest price found: $'+state.best,`All 6 products checked. ${products[state.bestIndex][0]} wins; the equal price at Ridge does not replace it because the test is strictly <.`)}}
 if(kind==='board'){const b=boards[scenario];if(b[i]){highlight([2,3,4]);status('Occupied square → continue',`Square ${i} contains ${b[i]}. Skip the rest of this iteration.`)}else{const score=scoreMove(b,i);state.scores[i]=score;const better=score>state.best;if(better){state.best=score;state.bestIndex=i}highlight(better?[2,3,5,6,7,8]:[2,3,5,6]);status(better?'Remember a better move':'Keep the current best move',`Square ${i} scores ${score>0?'+':''}${score}. ${better?'Update best_move to '+i+'.':'Its score does not beat '+state.best+'.'}`)}if(i===8){finish();status('Best next move: square '+state.bestIndex,`All 9 squares visited. X ${state.best===1?'can force a win':state.best===0?'can secure a draw':'cannot avoid losing with perfect opposing play'}. The green square is the recommended move.`)}}
 if(kind==='password'){state.found=!strong&&guesses[i]==='welcome';highlight(state.found?[1,2,3,4,5]:protectedLogin&&i===2?[1,2,3,6,7]:[1,2,3,6]);if(state.found){finish();status('Match found → break',`“${guesses[i]}” matches on attempt ${i+1}. The loop exits; remaining passwords are never tried.`)}else if(protectedLogin&&i===2){finish();status('Account locked → break','Three attempts failed. The lockout stops the loop before it reaches “welcome”.')}else if(i===5){finish();status('List exhausted. No match.','Every candidate failed. The for loop ends naturally, with found still False.')}else status('No match. Try the next candidate.',`Attempt ${i+1}: “${guesses[i]}” fails. found stays False; the loop advances to the next index.`)}render();}
$('#step').onclick=()=>{stop();step()};$('#reset').onclick=reset;
function play(){if(timer){stop();return}if(state.done)return;$('#play').textContent='Ⅱ Pause';timer=setInterval(step,Number($('#speed').value))}
$('#play').onclick=play;$('#speed').onchange=()=>{if(timer){stop();play()}};
reset();
