const $=s=>document.querySelector(s);
const examples={
 integers:{func:'sum',type:'int · immutable',globals:['a','b','result'],locals:['num1','num2','total'],objects:[['I1','int','10',65],['I2','int','20',165],['I3','int','30',265],['I4','int','100',365]],code:['def sum(num1, num2):','    total = num1 + num2','    num1 = 100','    return total','','a = 10','b = 20','result = sum(a, b)','print(a, b, result)'],steps:[
 {line:0,title:'Define sum()',desc:'The function is ready; its local namespace does not exist yet.'},
 {line:5,g:{a:'I1'},visible:['I1'],title:'a → 10',desc:'The caller’s name a references an integer object.'},
 {line:6,g:{a:'I1',b:'I2'},visible:['I1','I2'],title:'b → 20',desc:'The caller’s name b references another integer object.'},
 {line:7,g:{a:'I1',b:'I2'},l:{num1:'I1',num2:'I2'},visible:['I1','I2'],frame:true,title:'Create the local names',desc:'num1 and a reference the same object; so do num2 and b.'},
 {line:1,g:{a:'I1',b:'I2'},l:{num1:'I1',num2:'I2',total:'I3'},visible:['I1','I2','I3'],frame:true,title:'total → 30',desc:'Addition produces 30. total references that result; 10 and 20 stay unchanged.'},
 {line:2,g:{a:'I1',b:'I2'},l:{num1:'I4',num2:'I2',total:'I3'},visible:['I1','I2','I3','I4'],frame:true,title:'Reassign num1 → 100',desc:'Only the local name moves. a still references 10.'},
 {line:3,g:{a:'I1',b:'I2'},l:{num1:'I4',num2:'I2',total:'I3'},visible:['I1','I2','I3','I4'],frame:true,returned:'I3',title:'Return 30',desc:'The return value is the object referenced by total.'},
 {line:7,g:{a:'I1',b:'I2',result:'I3'},visible:['I1','I2','I3','I4'],returned:'I3',exited:true,title:'Back to the caller',desc:'The call ends. Local names disappear; result now references 30.'},
 {line:8,g:{a:'I1',b:'I2',result:'I3'},visible:['I1','I2','I3','I4'],returned:'I3',exited:true,output:'10 20 30',title:'a is still 10',desc:'Reassigning num1 did not reassign a.'}
 ]},
 lists:{func:'sum_list',type:'list · mutable',globals:['values','result'],locals:['nums','total','num'],objects:[['L1','list','',65],['I1','int','10',65],['I2','int','20',150],['I3','int','30',235],['I4','int','100',320],['I0','int','0',405],['I6','int','60',490]],code:['def sum_list(nums):','    total = 0','    for num in nums:','        total += num','    nums.append(100)','    return total','','values = [10, 20, 30]','result = sum_list(values)','print(values)','print(result)'],steps:[
 {line:0,title:'Define sum_list()',desc:'The function is ready; its local namespace does not exist yet.'},
 {line:7,g:{values:'L1'},visible:['L1','I1','I2','I3'],items:['I1','I2','I3'],title:'values → L1',desc:'One list object holds three references to integer objects.'},
 {line:8,g:{values:'L1'},l:{nums:'L1'},visible:['L1','I1','I2','I3'],items:['I1','I2','I3'],frame:true,title:'nums → the same list',desc:'A new local name is created. The list is not copied.'},
 {line:1,g:{values:'L1'},l:{nums:'L1',total:'I0'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'total → 0',desc:'The local accumulator starts at zero.'},
 {line:2,g:{values:'L1'},l:{nums:'L1',total:'I0',num:'I1'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'Iteration 1 · num → 10',desc:'num references the first item in the list.'},
 {line:3,g:{values:'L1'},l:{nums:'L1',total:'I1',num:'I1'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'total → 10',desc:'0 + 10 produces 10. The name total is rebound; no integer is mutated.'},
 {line:2,g:{values:'L1'},l:{nums:'L1',total:'I1',num:'I2'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'Iteration 2 · num → 20',desc:'num advances to the next item.'},
 {line:3,g:{values:'L1'},l:{nums:'L1',total:'I3',num:'I2'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'total → 30',desc:'10 + 20 produces 30. total changes its reference again.'},
 {line:2,g:{values:'L1'},l:{nums:'L1',total:'I3',num:'I3'},visible:['L1','I1','I2','I3','I0'],items:['I1','I2','I3'],frame:true,title:'Iteration 3 · num → 30',desc:'num references the last item.'},
 {line:3,g:{values:'L1'},l:{nums:'L1',total:'I6',num:'I3'},visible:['L1','I1','I2','I3','I0','I6'],items:['I1','I2','I3'],frame:true,title:'total → 60',desc:'30 + 30 produces 60. The three original items have been summed.'},
 {line:4,g:{values:'L1'},l:{nums:'L1',total:'I6',num:'I3'},visible:['L1','I1','I2','I3','I4','I0','I6'],items:['I1','I2','I3','I4'],frame:true,mutated:'L1',title:'Mutate L1 · append 100',desc:'The same list gains a fourth item. Both values and nums see the change.'},
 {line:5,g:{values:'L1'},l:{nums:'L1',total:'I6',num:'I3'},visible:['L1','I1','I2','I3','I4','I0','I6'],items:['I1','I2','I3','I4'],frame:true,returned:'I6',title:'Return 60',desc:'Appending to the list does not change the already-computed total.'},
 {line:8,g:{values:'L1',result:'I6'},visible:['L1','I1','I2','I3','I4','I0','I6'],items:['I1','I2','I3','I4'],returned:'I6',exited:true,title:'Back to the caller',desc:'The local names disappear. values still references the modified list L1.'},
 {line:9,g:{values:'L1',result:'I6'},visible:['L1','I1','I2','I3','I4','I0','I6'],items:['I1','I2','I3','I4'],returned:'I6',exited:true,output:'[10, 20, 30, 100]',title:'The caller sees 100',desc:'Mutating the shared list was visible outside the function.'},
 {line:10,g:{values:'L1',result:'I6'},visible:['L1','I1','I2','I3','I4','I0','I6'],items:['I1','I2','I3','I4'],returned:'I6',exited:true,output:'[10, 20, 30, 100]\n60',title:'The result is 60',desc:'The sum was computed before the append.'}
 ]}
};
let mode='integers',index=0,timer=null,animation=0,edges=new Map();
const ns='http://www.w3.org/2000/svg';
function stop(){clearInterval(timer);timer=null;$('#play').textContent='▶ Play'}
function binding(name,prefix){return `<div class="binding hidden" id="${prefix}-${name}"><span>${name}</span><span class="port" aria-hidden="true"></span></div>`}
function setup(next){stop();cancelAnimationFrame(animation);edges.clear();$('#paths').innerHTML='';mode=next;index=0;const e=examples[mode];$('#integers').setAttribute('aria-pressed',mode==='integers');$('#lists').setAttribute('aria-pressed',mode==='lists');$('#diagram').classList.toggle('list-mode',mode==='lists');$('#globals').innerHTML=e.globals.map(n=>binding(n,'g')).join('');$('#locals').innerHTML=e.locals.map(n=>binding(n,'l')).join('');$('#function-name').innerHTML=`${e.func}() <span>local</span>`;$('#type-label').textContent=e.type;$('#code').innerHTML=e.code.map((l,i)=>`<span class="line" data-line="${i}"><span class="ln">${i+1}</span>${l.replaceAll('&','&amp;').replaceAll('<','&lt;')}</span>`).join('');$('#objects').innerHTML=e.objects.map(([id,type,value,y])=>`<div class="object ${type==='list'?'list-object':''}" id="obj-${id}" style="top:${Math.round(y*.8)}px"><div class="meta"><span>${type}</span><span>${id}</span></div>${type==='list'?`<div class="value">[ … ]</div>${[0,1,2,3].map(i=>`<div class="list-slot hidden" id="slot-${i}"><span>[${i}]</span><span class="port" aria-hidden="true"></span></div>`).join('')}`:`<div class="value">${value}</div>`}</div>`).join('');render(false)}
function render(animate=true){const e=examples[mode],s=e.steps[index],prior=e.steps[Math.max(0,index-1)],used=new Set([...Object.values(s.g||{}),...Object.values(s.l||{}),...(s.items||[]),...(s.returned?[s.returned]:[])]);for(const [prefix,names,values] of [['g',e.globals,s.g||{}],['l',e.locals,s.l||{}]])for(const name of names){const node=$(`#${prefix}-${name}`),changed=values[name]&&values[name]!==((prefix==='g'?prior.g:prior.l)||{})[name];node.classList.toggle('hidden',!values[name]);node.setAttribute('aria-hidden',!values[name]);node.classList.toggle('changed',!!changed);node.setAttribute('aria-label',`${name}${values[name]?' references '+values[name]:' not bound'}`)}for(const [id] of e.objects){const node=$('#obj-'+id);node.classList.toggle('visible',(s.visible||[]).includes(id));node.setAttribute('aria-hidden',!(s.visible||[]).includes(id));node.classList.toggle('unreferenced',!used.has(id));node.classList.toggle('changed',s.mutated===id||(s.visible||[]).includes(id)&&!(prior.visible||[]).includes(id))}for(let i=0;i<4;i++){const slot=$('#slot-'+i);if(slot){slot.classList.toggle('hidden',!s.items?.[i]);slot.setAttribute('aria-hidden',!s.items?.[i]);slot.classList.toggle('changed',!!s.items?.[i]&&!prior.items?.[i])}}$('#local-frame').classList.toggle('inactive',!s.frame);$('#frame-label').textContent=s.frame?'Call active':s.exited?'Call finished':'Not called';$('#counter').textContent=`${index+1} / ${e.steps.length}`;$('#action').textContent=s.title;$('#description').textContent=s.desc;$('#output').textContent=s.output||'—';$('#return-value').textContent=s.returned?`${e.objects.find(o=>o[0]===s.returned)[2]} · ${s.returned}`:'—';document.querySelectorAll('.line').forEach((n,i)=>n.classList.toggle('active',s.line===i));$('#back').disabled=index===0;$('#step').disabled=index===e.steps.length-1;$('#play').disabled=index===e.steps.length-1;if(index===e.steps.length-1)stop();drawArrows(animate)}
function drawArrows(animate=true){cancelAnimationFrame(animation);const s=examples[mode].steps[index],targets=[];for(const [key,id] of Object.entries(s.g||{}))targets.push(['g-'+key,id]);for(const [key,id] of Object.entries(s.l||{}))targets.push(['l-'+key,id]);for(const [i,id] of (s.items||[]).entries())targets.push(['slot-'+i,id]);const box=$('#diagram').getBoundingClientRect(),wanted=new Set(targets.map(t=>t[0])),motions=[];for(const [key,edge] of edges){if(!wanted.has(key)){edge.path.remove();edges.delete(key)}}for(const [key,id] of targets){const a=$('#'+key).getBoundingClientRect(),b=$('#obj-'+id).getBoundingClientRect(),end=[a.right-box.left+2,a.top+a.height/2-box.top,b.left-box.left-4,b.top+b.height/2-box.top];let edge=edges.get(key);if(!edge){const path=document.createElementNS(ns,'path');path.setAttribute('class','reference-arrow');$('#paths').append(path);edge={path,coords:[end[0],end[1],end[0],end[1]],id:null};edges.set(key,edge)}edge.path.classList.toggle('changed',edge.id!==id);motions.push({edge,start:edge.coords.slice(),end});edge.id=id}const duration=animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches?480:0,start=performance.now();function tick(now){const f=duration?Math.min(1,(now-start)/duration):1,t=1-Math.pow(1-f,3);for(const m of motions){const c=m.start.map((n,i)=>n+(m.end[i]-n)*t),[x,y,tx,ty]=c,curve=Math.max(22,(tx-x)*.48);m.edge.coords=c;m.edge.path.setAttribute('d',`M ${x} ${y} C ${x+curve} ${y}, ${tx-curve} ${ty}, ${tx} ${ty}`)}if(f<1)animation=requestAnimationFrame(tick)}animation=requestAnimationFrame(tick)}
function advance(){if(index<examples[mode].steps.length-1){index++;render()}}
$('#step').onclick=()=>{stop();advance()};$('#back').onclick=()=>{stop();if(index>0){index--;render()}};$('#reset').onclick=()=>setup(mode);$('#integers').onclick=()=>setup('integers');$('#lists').onclick=()=>setup('lists');function play(){if(timer){stop();return}$('#play').textContent='Ⅱ Pause';timer=setInterval(advance,Number($('#speed').value))}$('#play').onclick=play;$('#speed').onchange=()=>{if(timer){stop();play()}};new ResizeObserver(()=>drawArrows(false)).observe($('#diagram'));setup('integers');
