const $=s=>document.querySelector(s),M=LargeDemo,kind=document.body.dataset.demo;
const config={price:{title:'Compare 600 products.',name:'600 similar bottles',original:'index.html',count:600,lines:['best_price = float("inf")','best_product = None','for i in range(len(products)):','    price = products[i]["price"]','    if price < best_price:','        best_price = price','        best_product = products[i]["name"]'],note:'Every tile is one bottle. Height and brightness are not prices; select a tile to inspect its price. The loop must visit all 600 items. Equal prices keep the first match.'},go:{title:'Scan a 19 × 19 Go board.',name:'Black to move · 361 intersections',original:'tic-tac-toe.html',count:361,lines:['best_score = -1','best_move = None','for i in range(19 * 19):','    move = evaluate_move(board, i)','    if not move.legal:','        continue','    if move.score > best_score:','        best_score = move.score','        best_move = i'],note:'evaluate_move skips occupied points and suicide moves, removes captured white groups, then scores 100 × captures + liberties of the resulting black group. Liberties are adjacent empty points. This is a one-turn heuristic, not an expert Go engine. This fixed position has no ko restriction; repetition rules and whole-game territory strategy are outside this demo.'},password:{title:'Try 6,000 password candidates.',name:'Local password simulation',original:'passwords.html',count:6000,lines:['found = False','for i in range(len(candidates)):','    guess = candidates[i]','    if guess == simulated_password:','        found = True','        break'],note:'The list contains 20 familiar examples followed by generated three-digit suffix variants, not a ranked dataset of 6,000 common passwords. This demo compares strings locally, with no network, real accounts, hashing, rate limits, or authentication server. Its speed is not a measurement of real password cracking.'}}[kind];
const data=kind==='price'?M.products:kind==='go'?M.board():M.passwords;
$('#app').innerHTML=`<div class="shell"><nav aria-label="Large demos"><a href="../index.html">All demos</a><a href="prices-large.html" ${kind==='price'?'aria-current="page"':''}>600 products</a><a href="go-large.html" ${kind==='go'?'aria-current="page"':''}>Go board</a><a href="passwords-large.html" ${kind==='password'?'aria-current="page"':''}>6,000 passwords</a></nav><header><h1>${config.title}</h1></header><div class="scale-nav"><a href="${config.original}">Original version</a><a href="#" aria-current="page" id="largeLabel">Large version</a></div><main class="layout"><section class="panel"><div class="panel-head"><h2>${config.name}</h2><span class="tag" id="progress">Ready</span></div>${kind==='password'?'<label class="settings">Match location <select id="target"><option value="4872">Near the end · candidate 4,873</option><option value="12">Near the start · candidate 13</option><option value="absent">Not in the list</option></select></label>':''}<div class="metrics"><div><small>Items visited</small><strong id="visited">0</strong></div><div><small>Computer loop time</small><strong id="time">—</strong></div><div><small>At 1 item / second</small><strong id="human">—</strong></div></div><div class="visual"><canvas id="canvas" width="900" height="${kind==='go'?900:540}" role="img" aria-label="${config.name}; details below"></canvas><div class="legend">Gray = unvisited · teal = visited · amber = current · green outline = best / match</div><p class="detail" id="detail"></p><label class="settings" style="padding:8px 0;border:0">Inspect ${kind==='go'?'intersection':'item'} <input id="inspect" type="number" min="1" max="${config.count}" value="1" style="width:100px;padding:8px"></label></div><div class="progress-track"><div class="progress-fill" id="fill"></div></div><div class="status" aria-live="polite"><strong id="statusTitle">Ready</strong><span id="statusText">Step through a few items, then run the entire loop at computer speed.</span></div><div class="controls"><button id="step">Step →</button><button id="play">▶ Slow scan</button><button id="reset">Reset</button><button class="primary" id="run">Run at computer speed</button></div><div class="benchmark">Computer run starts from item 1. Time measures JavaScript loop work in this browser, excluding drawing. Python shows the same algorithm. The 1-item/second comparison is an illustration, not a measured human speed.</div></section><section class="panel code-panel"><div class="panel-head"><h2>The loop</h2><span class="tag">Python</span></div><pre class="code"><code id="code"></code></pre><div class="variables" id="variables"></div><p class="explain" id="explain"></p><details><summary>${kind==='go'?'How the move score works':kind==='password'?'About the candidates and timing':'About the products'}</summary><p>${config.note}</p></details></section></main><footer>Click a tile or use the item number to inspect it.</footer></div>`;
$('#largeLabel').onclick=e=>e.preventDefault();
$('#code').innerHTML=config.lines.map((l,i)=>`<span class="line"><span class="ln">${i+1}</span>${l.replaceAll('&','&amp;').replaceAll('<','&lt;')}</span>`).join('');
let state,timer=null,selected=0,targetIndex=4872;
const canvas=$('#canvas'),ctx=canvas.getContext('2d');
function halt(){clearInterval(timer);timer=null;$('#play').textContent='▶ Slow scan'}
function init(){state={i:-1,best:kind==='price'?Infinity:-1,bestIndex:null,found:false,done:false,scores:[],ms:null,evaluated:0,lines:kind==='password'?[0]:[0,1]};selected=0}
function one(){if(state.done)return;const i=++state.i;if(kind==='price'){state.lines=[2,3,4];if(data[i].cents<state.best){state.best=data[i].cents;state.bestIndex=i;state.lines.push(5,6)}}else if(kind==='go'){const move=M.goScore(data,i);state.scores[i]=move;state.lines=move.legal?[2,3,4,6]:[2,3,4,5];if(move.legal){state.evaluated++;if(move.score>state.best){state.best=move.score;state.bestIndex=i;state.lines.push(7,8)}}}else {state.lines=[1,2,3];if(data[i]===(targetIndex===null?'a-long-unique-passphrase-not-in-this-list':data[targetIndex])){state.found=true;state.bestIndex=i;state.done=true;state.lines.push(4,5)}}if(i===config.count-1)state.done=true}
function seconds(n){return n<60?n+' s':Math.floor(n/60)+' min'+(n%60?' '+n%60+' s':'')}
function cash(n){return '$'+(n/100).toFixed(2)}
function coord(i){return String.fromCharCode(65+i%19+(i%19>=8?1:0))+(19-Math.floor(i/19))}
function describe(i){if(kind==='price')return `${data[i].name} · ${cash(data[i].cents)} · index ${i}`;if(kind==='password')return `Candidate ${i+1}: ${data[i]} · ${i>state.i?'not tried':state.found&&i===state.bestIndex?'MATCH':'no match'}`;const m=state.scores[i];return `${coord(i)} · index ${i} · ${data[i]===1?'black stone':data[i]===2?'white stone':!m?'empty · not evaluated':!m.legal?'skip: '+m.reason:`captures ${m.captured} · liberties ${m.liberties} · score ${m.score}`}`}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(kind==='go'){ctx.fillStyle='#e8c68e';ctx.fillRect(0,0,900,900);ctx.strokeStyle='#83683f';ctx.lineWidth=1.5;for(let j=0;j<19;j++){const p=45+j*45;ctx.beginPath();ctx.moveTo(45,p);ctx.lineTo(855,p);ctx.moveTo(p,45);ctx.lineTo(p,855);ctx.stroke()}for(let i=0;i<361;i++){const x=45+(i%19)*45,y=45+Math.floor(i/19)*45;if(data[i]){ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fillStyle=data[i]===1?'#172b32':'#fffcf3';ctx.fill();ctx.strokeStyle='#776b52';ctx.stroke()}else if(i<=state.i){ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fillStyle='#267c70';ctx.fill()}if(i===state.i||i===state.bestIndex||i===selected){ctx.beginPath();ctx.arc(x,y,21,0,Math.PI*2);ctx.strokeStyle=i===state.bestIndex?'#058440':i===state.i?'#bd6b00':'#5972a7';ctx.lineWidth=4;ctx.stroke();ctx.lineWidth=1.5}}}else{const cols=kind==='price'?30:100,rows=config.count/cols,w=900/cols,h=540/rows;for(let i=0;i<config.count;i++){const x=(i%cols)*w,y=Math.floor(i/cols)*h;ctx.fillStyle=i===state.bestIndex?'#087e43':i===state.i?'#cb800b':i<=state.i?'#559b8e':'#dce3da';ctx.fillRect(x+1,y+1,w-2,h-2);if(i===state.bestIndex||i===selected){ctx.strokeStyle=i===state.bestIndex?'#004c26':'#263b83';ctx.lineWidth=kind==='price'?3:2;ctx.strokeRect(x+1,y+1,w-2,h-2)}}}canvas.setAttribute('aria-label',`${config.name}. ${state.i+1} visited. ${state.bestIndex===null?'No best item yet.':'Best or matching item: '+describe(state.bestIndex)}`)}
function update(){const n=state.i+1;$('#visited').textContent=n.toLocaleString();$('#progress').textContent=`${n.toLocaleString()} / ${config.count.toLocaleString()}`;$('#human').textContent=n?seconds(n):'—';$('#time').textContent=state.ms===null?'—':state.ms<.1?'< 0.1 ms':state.ms.toFixed(2)+' ms';$('#fill').style.width=100*n/config.count+'%';$('#step').disabled=state.done;$('#play').disabled=state.done;$('#inspect').value=selected+1;$('#detail').textContent=describe(selected);let pairs,explain,title,detail;
 if(kind==='price'){pairs=[['i',state.i<0?'—':state.i],['best_price',state.best===Infinity?'∞':cash(state.best)],['best_product',state.bestIndex===null?'None':data[state.bestIndex].name]];explain='Scan every price. Replace the best only when a lower price appears.';title=state.done?'Lowest price: '+cash(state.best):n?'Best so far: '+cash(state.best):'Ready';detail=state.done?`${data[state.bestIndex].name} wins after all 600 comparisons.`:n?describe(state.i):'Step through a few products, then run all 600 comparisons.';}
 else if(kind==='go'){pairs=[['i',state.i<0?'—':state.i],['best_score',state.best],['best_move',state.bestIndex===null?'None':coord(state.bestIndex)],['legal moves checked',state.evaluated]];explain='Score = 100 × captured stones + liberties. Black chooses the highest score; this simple heuristic does not predict future turns.';title=state.done?'Heuristic choice: '+coord(state.bestIndex):n?'Scanning intersections':'Ready';detail=state.done?`${describe(state.bestIndex)}. All 361 intersections scanned.`:n?describe(state.i):'Visit all intersections, skip occupied points, and compare legal moves.';}
 else{pairs=[['i',state.i<0?'—':state.i],['guess',state.i<0?'—':data[state.i]],['found',state.found?'True':'False']];explain='Try one candidate per iteration. break ends the loop immediately on a match. These are generated common-pattern guesses in a local simulation.';title=state.found?'Match found → break':state.done?'List exhausted. No match.':n?'Trying candidates':'Ready';detail=state.found?`“${data[state.i]}” matched after ${n.toLocaleString()} attempts. ${(config.count-n).toLocaleString()} candidates were never tried.`:state.done?'All 6,000 candidates failed.':n?describe(state.i):'Step through a few candidates, then run thousands of comparisons.';}
 $('#variables').innerHTML=pairs.map(([k,v])=>`<div class="variable"><small>${k}</small><strong>${v}</strong></div>`).join('');$('#explain').textContent=explain;$('#statusTitle').textContent=title;$('#statusText').textContent=detail;document.querySelectorAll('.line').forEach((e,i)=>e.classList.toggle('active',state.lines.includes(i)));draw();if(state.done)halt();}
function reset(){halt();init();update()}
function step(){one();selected=Math.max(0,state.i);update()}
$('#step').onclick=()=>{halt();step()};$('#play').onclick=()=>{if(timer){halt();return}$('#play').textContent='Ⅱ Pause';timer=setInterval(step,500)};$('#reset').onclick=reset;
$('#run').onclick=()=>{halt();init();const start=performance.now();for(let i=0;i<config.count;i++){one();if(state.done)break}state.ms=performance.now()-start;selected=state.bestIndex??state.i;update()};
if(kind==='password')$('#target').onchange=e=>{targetIndex=e.target.value==='absent'?null:Number(e.target.value);reset()};
$('#inspect').oninput=e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=config.count){selected=n-1;$('#detail').textContent=describe(selected);draw()}};
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*900/r.width,y=(e.clientY-r.top)*canvas.height/r.height;let i;if(kind==='go'){const col=Math.round((x-45)/45),row=Math.round((y-45)/45);if(col<0||col>18||row<0||row>18)return;i=row*19+col}else{const cols=kind==='price'?30:100;i=Math.floor(y/(540/(config.count/cols)))*cols+Math.floor(x/(900/cols))}if(i>=0&&i<config.count){selected=i;$('#inspect').value=i+1;$('#detail').textContent=describe(i);draw()}};
reset();
